# Generated by Django 6.0.2 on 2026-02-18 20:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('UI/UX', 'Ui/Ux'), ('DATA SCIENCE', 'data science'), ('PYTHON DEVELOPING', 'python_developing'), ('FLUTTER', 'flutter'), ('DATA ANALATICS', 'data analytics'), ('REACT', 'react'), ('FRONT END DEVELOPING', 'front end development'), ('BACK END DEVELOPING', 'back end development'), ('DEVOPS', 'devops'), ('CLOUD', 'cloud')], default='UI/UX', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('complaint_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_cloud_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('UI/UX', 'Ui/Ux'), ('DATA SCIENCE', 'data science'), ('PYTHON DEVELOPING', 'python_developing'), ('FLUTTER', 'flutter'), ('DATA ANALATICS', 'data analytics'), ('REACT', 'react'), ('FRONT END DEVELOPING', 'front end development'), ('BACK END DEVELOPING', 'back end development'), ('DEVOPS', 'devops'), ('CLOUD', 'cloud')], default='UI/UX', max_length=100)),
                ('payroll_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_cloud_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100)),
                ('work_duration', models.CharField()),
                ('employee_name', models.CharField()),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('UI/UX', 'Ui/Ux'), ('DATA SCIENCE', 'data science'), ('PYTHON DEVELOPING', 'python_developing'), ('FLUTTER', 'flutter'), ('DATA ANALATICS', 'data analytics'), ('REACT', 'react'), ('FRONT END DEVELOPING', 'front end development'), ('BACK END DEVELOPING', 'back end development'), ('DEVOPS', 'devops'), ('CLOUD', 'cloud')], default='UI/UX', max_length=100)),
                ('work_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_cloud_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), (' MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY  ', ' JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER  ', 'NOVEMBER'), ('DECEMBER  ', 'DECEMBER')], default='JANUARY', max_length=100)),
                ('days', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], default='MONDAY', max_length=100)),
                ('department', models.CharField(choices=[('UI/UX', 'Ui/Ux'), ('DATA SCIENCE', 'data science'), ('PYTHON DEVELOPING', 'python_developing'), ('FLUTTER', 'flutter'), ('DATA ANALATICS', 'data analytics'), ('REACT', 'react'), ('FRONT END DEVELOPING', 'front end development'), ('BACK END DEVELOPING', 'back end development'), ('DEVOPS', 'devops'), ('CLOUD', 'cloud')], default='UI/UX', max_length=100)),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hr_cloud_app.employee')),
                ('work_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hr_cloud_app.work')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_hr', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('hr_details', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
