# Generated by Django 6.0.2 on 2026-02-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='employee_name',
        ),
    ]
