# Generated by Django 6.0.2 on 2026-02-28 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hr_cloud_app.employee'),
            preserve_default=False,
        ),
    ]
