# Generated by Django 6.0.2 on 2026-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0002_remove_work_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='employee_name',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
    ]
