# Generated by Django 6.0.2 on 2026-02-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0003_work_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='employee_details_id',
            new_name='payroll_details',
        ),
    ]
