# Generated by Django 6.0.2 on 2026-02-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0004_rename_employee_details_id_payroll_payroll_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='payroll_details',
            new_name='employee_details_id',
        ),
    ]
