# Generated by Django 6.0.2 on 2026-02-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0005_rename_payroll_details_payroll_employee_details_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='employee_details_id',
            new_name='payroll_details',
        ),
    ]
