# Generated by Django 6.0.2 on 2026-02-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0006_rename_employee_details_id_payroll_payroll_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('complaint_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_cloud_app.employee')),
            ],
        ),
    ]
