# Generated by Django 6.0.2 on 2026-02-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0007_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_name',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('UI/UX', 'Ui/Ux'), ('DATA SCIENCE', 'data science'), ('PYTHON DEVELOPING', 'python_developing'), ('FLUTTER', 'flutter'), ('DATA ANALATICS', 'data analytics'), ('REACT', 'react'), ('FRONT END DEVELOPING', 'front end development'), ('BACK END DEVELOPING', 'back end development'), ('DEVOPS', 'devops'), ('CLOUD', 'cloud')], default='UI/UX', max_length=100),
        ),
    ]
