# Generated by Django 6.0.2 on 2026-02-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0008_remove_complaint_complaint_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('replay_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_cloud_app.complaint')),
            ],
        ),
    ]
