# Generated by Django 6.0.2 on 2026-02-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0009_replay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replay',
            new_name='Reply',
        ),
    ]
