# Generated by Django 6.0.2 on 2026-02-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_cloud_app', '0010_rename_replay_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replay_details',
        ),
    ]
